name: Matrix-Multiplication CI

on: [ push, pull_request ]

concurrency:
  group: '${{ github.event_name }}-${{ github.ref }}'
  cancel-in-progress: true

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        id: checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup MPI
        id: mpi-setup
        uses: mpi4py/setup-mpi@v1
        with:
          mpi: 'openmpi'
      - name: Verify MPI
        id: mpi-verify
        run: ompi_info

      - name: Setup CMake
        id: cmake-setup
        uses: jwlawson/actions-setup-cmake@v2
      - name: Verify Cmake
        id: cmake-verify
        run: cmake --version
      - name: Configure CMake
        id: cmake-configuration
        run: cmake -S . -B build

      - name: Build
        id: build
        run: cmake --build build

      - name: Run Tests
        id: unit-tests
        run: ctest --test-dir build --output-on-failure --output-log test.log

      - name: Setup Cppcheck
        id: cppcheck-setup
        run: sudo apt-get install cppcheck
      - name: Verify Cppcheck
        id: cppcheck-verify
        run: cppcheck --version
      - name: S.C.A. :: Cppcheck
        id: sca-cppcheck
        run: cppcheck --enable=all --inconclusive --std=c++17 src

      - name: Setup Singularity dependencies
        id: singularity-dep-setup
        run: |
          sudo apt-get update && sudo apt-get install -y \
            autoconf \
            automake \
            cryptsetup \
            git \
            libfuse-dev \
            libglib2.0-dev \
            libseccomp-dev \
            libtool \
            pkg-config \
            runc \
            squashfs-tools \
            squashfs-tools-ng \
            uidmap \
            wget \
            zlib1g-dev
      - name: Setup Go
        id: go-setup
        run: |
          export GO_VERSION=1.22.3 GO_OS=linux GO_ARCH=amd64
          wget https://go.dev/dl/go$GO_VERSION.$GO_OS-$GO_ARCH.tar.gz
          sudo tar -C /usr/local -xzvf go$GO_VERSION.$GO_OS-$GO_ARCH.tar.gz
          rm go$GO_VERSION.$GO_OS-$GO_ARCH.tar.gz
          echo 'export PATH=$PATH:/usr/local/go/bin' >> $GITHUB_ENV
          echo 'PATH=$PATH:/usr/local/go/bin' >> $GITHUB_PATH
      - name: Verify Go
        id: go-verify
        run: go version
      - name: Setup Singularity
        id: singularity-setup
        run: |
          export SINGULARITY_VERSION=4.1.3
          wget https://github.com/sylabs/singularity/releases/download/v${SINGULARITY_VERSION}/singularity-ce-${SINGULARITY_VERSION}.tar.gz
          tar -xzf singularity-ce-${SINGULARITY_VERSION}.tar.gz
          cd singularity-ce-${SINGULARITY_VERSION}
          ./mconfig
          make -C builddir
          sudo make -C builddir install
      - name: Verify Singularity
        id: singularity-verify
        run: singularity --version

      - name: Build Singularity image
        id: singularity-build
        run: sudo -E singularity build mx-multiplication.sif SingularityFile.def
      - name: Upload Singularity image
        id: singularity-image-upload
        uses: actions/upload-artifact@v4
        with:
          name: mx-multiplication.sif
          path: mx-multiplication.sif
          if-no-files-found: error
          retention-days: 10
