name: Matrix-Multiplication Webhook Acceptor

on:
  # When a webhook is received at the URL on the bottom
  # and the event type matches,
  # a workflow may be triggered to run some actions.
  #
  # https://api.github.com/repos/{user}/{repo}/dispatches
  # {
  #  "event_type": <type>,
  #  "client_payload": {
  #    ...
  #  }
  # }
  repository_dispatch:
    types:
      - result-notification
  # When a 'result-notification' webhook is received at the URL on the bottom,
  # meaning that the remote computation is either failed or completed successfully,
  # the Telegram BOT notifies about the outcome of the computation on the cluster.
  #
  # https://api.github.com/repos/danielepiano/SE4HPC-devops-project-ii/dispatches
  # {
  #  "event_type": result-notification,
  #  "client_payload": {
  #    "passed": boolean,
  #    "log": "string",
  #    "filename": "string"
  #  }
  # }

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Notification | Success via Telegram se4hpc_ci_bot
        if: ${{ github.event.client_payload.passed }}
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_SE4HPC_CI_BOT_TOKEN }}
          message: |
            The job has completed its execution on cluster!!! :DDD
            Here are some logs...

            ${{ github.event.client_payload.log }}


            You can check this outcome on ${{ github.event.client_payload.filename }}

      - name: Notification | Failure via Telegram se4hpc_ci_bot
        if: ${{ !github.event.client_payload.passed }}
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_SE4HPC_CI_BOT_TOKEN }}
          message: |
            The job has failed its execution on cluster :(((
            Here are some logs...
            
            ${{ github.event.client_payload.log }}


            See more details on file ${{ github.event.client_payload.filename }}
